### ISSUE TITLE
Select by day: Logic layer

### ISSUE THREAD

**Issue by Anassm** [Anassm/Project-B-Gangrenners#252]
[As a user i want to choose a day and see al movies that day](https://github.com/users/Anassm/projects/9/views/1?filterQuery=Item%3A%22User+story%22+sprint%3A%22Sprint+4%22&pane=issue&itemId=81904993)

- [x] string DisplayMovies(DateTime dayToShow) -> Show all movies from which a showtime is happening that day (check with finance dashboard for overloading)
- [x] string DisplayShowtimes(DateTime dayToShow, int movieId) -> Show all showtimes based on whatever movie and day has been selected with method above
- [x] List MovieModel GetMovies(DateTime dayToShow) -> Show all movies from that day

**Comment by RedRoan04** [comment]
- [ ] GetShowtimesById(Datetime day)
