### ISSUE TITLE
Movie and time: Data access and Data source seats

### ISSUE THREAD

**Issue by RedRoan04** [Anassm/Project-B-Gangrenners#5]
[As a user I want to select a movie, time and select a seat](https://github.com/users/Anassm/projects/9/views/1?pane=issue&itemId=81900011)

- [x] Create JSON files with following data (Data Sources):
    - [x] Seats
 -------------------------------------------------------------------------------------------------------
- [ ] Create a SeatsAccess class (Data Access)
    - [ ] LoadAll: read and return all Seats
    - [ ] WriteAll: Write all supplied Seats
 -------------------------------------------------------------------------------------------------------
- [ ] Create SeatsModel: Properties: ID, HallID, TimeID, Type, Price, Availability (Data Models)

**Comment by jenskon** [comment]
seats.json were added during the "Movie and time: Data access and Data source Movies" issue.
