### ISSUE TITLE
Movie and time: Testing - Create test plan

### ISSUE THREAD

**Issue by RedRoan04** [Anassm/Project-B-Gangrenners#50]
[As a user I want to select a movie, time and select a seat](https://github.com/users/Anassm/projects/9/views/1?pane=issue&itemId=81900011)

- [ ] Create test plan

**Comment by jenskon** [comment]
the user should be able to see all movies, select a movie, choose a date and time for that movie, choose a seat for the movie

**Comment by jenskon** [comment]
when selecting a movie and the given movie does not exist, reask.
