### ISSUE TITLE
Movie and time: Data access and Data source showtimes

### ISSUE THREAD

**Issue by RedRoan04** [Anassm/Project-B-Gangrenners#6]
[As a user I want to select a movie, time and select a seat](https://github.com/users/Anassm/projects/9/views/1?pane=issue&itemId=81900011)

- [x] Create JSON files with following data (Data Sources):
    - [x] Showtimes

 -------------------------------------------------------------------------------------------------------
- [x] Create a ShowtimesAccess class (Data Access)
    - [x] LoadAll: read and return all Showtimes
    - [x] WriteAll: Write all supplied Showtimes
 -------------------------------------------------------------------------------------------------------
- [x] Create ShowtimesModel: Properties: ID, MoviesID, Time, Hall (Data Models)

**Comment by jenskon** [comment]
we are currently using a string type to store both the date and the time, later can we changed to datetime object.

**Comment by RedRoan04** [comment]
Possibly different fields/properties for date and time. But must be considered. Whats your opinion @jenskon @Anassm

**Comment by RedRoan04** [comment]
Decided for datetime together with po
