### ISSUE TITLE
Movie and time: Logic layer movie

### ISSUE THREAD

**Issue by RedRoan04** [Anassm/Project-B-Gangrenners#7]
[As a user I want to select a movie, time and select a seat](https://github.com/users/Anassm/projects/9/views/1?pane=issue&itemId=81900011)

- [x] Load all Movies in the constructor
-----------------------------------------------------------------------------
- [x] ~~CheckMovies~~ GetMovieByName: Find a movie using the given name
-----------------------------------------------------------------------------
- [x] ~~GetByIdMovie~~ GetMovieById: Find a movie using the given ID

**Comment by Anassm** [comment]
Changing CheckMovies & GetByIdMovie method names for more clarity.

**Comment by RedRoan04** [comment]
Contains not implemented for the bool function
